<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Part-1:-Wrangling-Data" data-toc-modified-id="Part-1:-Wrangling-Data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Part 1: Wrangling Data</a></span><ul class="toc-item"><li><span><a href="#CSV-Files" data-toc-modified-id="CSV-Files-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>CSV Files</a></span></li><li><span><a href="#Reading-Excel-Files" data-toc-modified-id="Reading-Excel-Files-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Reading Excel Files</a></span></li><li><span><a href="#Importing-Data-Directly-from-the-Web" data-toc-modified-id="Importing-Data-Directly-from-the-Web-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Importing Data Directly from the Web</a></span><ul class="toc-item"><li><span><a href="#Importing-Text-Files-from-the-Web" data-toc-modified-id="Importing-Text-Files-from-the-Web-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Importing Text Files from the Web</a></span></li><li><span><a href="#Importing-HTML-Files-from-the-Web" data-toc-modified-id="Importing-HTML-Files-from-the-Web-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Importing HTML Files from the Web</a></span></li><li><span><a href="#Importing-XML-Files-from-the-Web" data-toc-modified-id="Importing-XML-Files-from-the-Web-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Importing XML Files from the Web</a></span></li><li><span><a href="#Importing-JSON-Files-from-the-Web" data-toc-modified-id="Importing-JSON-Files-from-the-Web-1.3.4"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Importing JSON Files from the Web</a></span></li></ul></li></ul></li><li><span><a href="#Part-2:-Data-Munging" data-toc-modified-id="Part-2:-Data-Munging-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Part 2: Data Munging</a></span><ul class="toc-item"><li><span><a href="#Dataset-Morphology" data-toc-modified-id="Dataset-Morphology-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Dataset Morphology</a></span></li></ul></li><li><span><a href="#Slicing-and-Dicing" data-toc-modified-id="Slicing-and-Dicing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Slicing and Dicing</a></span></li><li><span><a href="#Handling-Missing-Values" data-toc-modified-id="Handling-Missing-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Handling Missing Values</a></span></li><li><span><a href="#Data-Profiling" data-toc-modified-id="Data-Profiling-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Data Profiling</a></span><ul class="toc-item"><li><span><a href="#Counts" data-toc-modified-id="Counts-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Counts</a></span></li><li><span><a href="#Ranges" data-toc-modified-id="Ranges-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Ranges</a></span></li><li><span><a href="#Quantiles" data-toc-modified-id="Quantiles-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Quantiles</a></span></li><li><span><a href="#Cuts" data-toc-modified-id="Cuts-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Cuts</a></span></li></ul></li><li><span><a href="#Load-Data" data-toc-modified-id="Load-Data-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Load Data</a></span></li><li><span><a href="#Check-Column-Names" data-toc-modified-id="Check-Column-Names-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Check Column Names</a></span></li><li><span><a href="#Write-a-function-that-will-take-a-row-of-a-DataFrame-and-print-out-the-song,-artist,-and-whether-or-not-the-release-date-is-&lt;-1970" data-toc-modified-id="Write-a-function-that-will-take-a-row-of-a-DataFrame-and-print-out-the-song,-artist,-and-whether-or-not-the-release-date-is-<-1970-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is &lt; 1970</a></span></li><li><span><a href="#Write-a-function-that-converts-cells-in-a-DataFrame-to-float-and-otherwise-replaces-them-with-np.nan" data-toc-modified-id="Write-a-function-that-converts-cells-in-a-DataFrame-to-float-and-otherwise-replaces-them-with-np.nan-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan</a></span></li><li><span><a href="#Apply-these-functions-to-your-dataset" data-toc-modified-id="Apply-these-functions-to-your-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Apply these functions to your dataset</a></span></li><li><span><a href="#Describe-the-new-float-only-DataFrame." data-toc-modified-id="Describe-the-new-float-only-DataFrame.-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Describe the new float-only DataFrame.</a></span></li></ul></div>

![alt text](https://i.imgur.com/1WaY7aA.png)


---



---



# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.14.2
Pandas:  0.23.4


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('../../data/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('../../data/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('../../data/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [3]:
#ANSWER:

bikes = pd.read_table("../../data/bikeshare.csv", header=0, sep=",")

bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [8]:
df = pd.read_excel('../../data/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
5             1          0.4           1.7          3.9           5.4   
6             1          0.3           1.4          3.4           4.6   
7             1          0.2           1.5          3.4           5.0   
8             1          0.2           1.4          2.9           4.4   
9             1          0.1           1.5          3.1           4.9   
10            1          0.2           1.5          3.7           5.4   
11            1          0.2           1.6          3.4           4.8   
12            1          0.1           1.4          3.0           4.8   
13            1          0.1           1.1          3.0           4.3   
14            1          0.2           1.2          4.0           5.8   
15            1          0.4           1.5          4.4           5.7   
16            1          0.4           1.3          3.9           5.4   
17            1          0.3           1.4          3.5           5.1   
18            1          0.3           1.7          3.8           5.7   
19            1          0.3           1.5          3.8           5.1   
20            1          0.2           1.7          3.4           5.4   
21            1          0.4           1.5          3.7           5.1   
22            1          0.2           1.0          3.6           4.6   
23            1          0.5           1.7          3.3           5.1   
24            1          0.2           1.9          3.4           4.8   
25            1          0.2           1.6          3.0           5.0   
26            1          0.4           1.6          3.4           5.0   
27            1          0.2           1.5          3.5           5.2   
28            1          0.2           1.4          3.4           5.2   
29            1          0.2           1.6          3.2           4.7   
..          ...          ...           ...          ...           ...   
120           3          2.3           5.7          3.2           6.9   
121           3          2.0           4.9          2.8           5.6   
122           3          2.0           6.7          2.8           7.7   
123           3          1.8           4.9          2.7           6.3   
124           3          2.1           5.7          3.3           6.7   
125           3          1.8           6.0          3.2           7.2   
126           3          1.8           4.8          2.8           6.2   
127           3          1.8           4.9          3.0           6.1   
128           3          2.1           5.6          2.8           6.4   
129           3          1.6           5.8          3.0           7.2   
130           3          1.9           6.1          2.8           7.4   
131           3          2.0           6.4          3.8           7.9   
132           3          2.2           5.6          2.8           6.4   
133           3          1.5           5.1          2.8           6.3   
134           3          1.4           5.6          2.6           6.1   
135           3          2.3           6.1          3.0           7.7   
136           3          2.4           5.6          3.4           6.3   
137           3          1.8           5.5          3.1           6.4   
138           3          1.8           4.8          3.0           6.0   
139           3          2.1           5.4          3.1           6.9   
140           3          2.4           5.6          3.1           6.7   
141           3          2.3           5.1          3.1           6.9   
142           3          1.9           5.1          2.7        

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [0]:
#ANSWER


### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [9]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [103]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [11]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0         5 2015-01-01 00:00:00         0
1         5 2015-01-01 00:00:01         0
10        5 2015-01-01 00:00:10         0
11        5 2015-01-01 00:00:11         0
12        8 2015-01-01 00:00:12         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [14]:
#ANSWER
print("There are {} rows and {} columns in bikes".format(bikes.shape[0], bikes.shape[1]))

There are 17379 rows and 17 columns in bikes


What are the column names in `bikes`?

In [15]:
#ANSWER

bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [16]:
#ANSWER

bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [17]:
#ANSWER

bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [19]:
#ANSWER

print(type(bikes['season']))
print(type(bikes[['season']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


How would we use object notation to show the first 4 rows of `atemp`?

In [24]:
#ANSWER

bikes['atemp'][:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [25]:
bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

KeyError: '[0] not in index'

What is the correct way to access the 1st row of the DataFrame by its index?

In [26]:
#ANSWER

bikes.iloc[0, ]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [27]:
#ANSWER

bikes.iloc[1, ]

instant                2
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     1
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.22
atemp             0.2727
hum                  0.8
windspeed              0
casual                 8
registered            32
cnt                   40
Name: 1, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

ANSWER: `isnull` creates a boolean mask of the Series/DataFrame showing which values are NaN.

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [4]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [5]:
#ANSWER

bikes.isnull().sum().sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [6]:
#ANSWER

bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid. `NaN` is short for Not a Number and usually indicates a missing value

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [38]:
#ANSWER

def divide_scalar(x, y):
    if x in [0, np.nan] or y in [0, np.nan]:
        return np.nan
    else:
        return x/y

In [39]:
divide_scalar(2.3, 4)

0.575

In [40]:
divide_scalar(2.3, 0)

nan

In [41]:
divide_scalar(2.3, np.nan)

nan

Apply the Pandas `isna` function to the following data objects:

In [30]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [34]:
#ANSWER

df = pd.DataFrame([x, y])
df.isna()

0
0  False
1   True

In [35]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [37]:
#ANSWER
pd.DataFrame(array).isna()

0      1      2
0  False   True  False
1  False  False   True

How is the pandas I/O parameter `na_values` used?

? ANSWER: The `na_values` parameter is used to covert custom missing value strings in the dataset into `np.nan` 

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [44]:
#ANSWER

bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [45]:
#ANSWER

for i in ['instant', 'dteday', 'windspeed']:
    print(i+ " min is {} and max is {}".format(bikes[i].min(), bikes[i].max()))

instant min is 1 and max is 17379
dteday min is 2011-01-01 and max is 2012-12-31
windspeed min is 0.0 and max is 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [47]:
bikes_min, bikes_max = (min(bikes.select_dtypes('number').min()), max(bikes.select_dtypes('number').max()))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [0]:
bikes['atemp'].quantile(0.5)

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [48]:
#ANSWER
bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [49]:
type(bikes['atemp'])

pandas.core.series.Series

In [50]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
15600    15601  2012-10-17       4   1    10   5        0        3   
4656      4657  2011-07-17       3   0     7  22        0        0   
13160    13161  2012-07-07       3   1     7  13        0        6   
7353      7354  2011-11-08       4   0    11   0        0        2   
3956      3957  2011-06-18       2   0     6  18        0        6   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
15600           1           2  0.36  0.3788  0.81     0.0000       2   
4656            0           1  0.72  0.6818  0.66     0.2239      65   
13160           0           2  0.96  0.8636  0.31     0.2537     116   
7353            1           1  0.34  0.3485  0.87     0.0896       0   
3956            0           2  0.74  0.6818  0.55     0.1940     118   

       registered  cnt  
15600          39   41  
4656          116  181  
13160         244  360  
7353           18   18  
3956          263  381

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [51]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [53]:
#ANSWER

print(type(atemp_level))

<class 'pandas.core.series.Series'>


Here is a random sample of `atemp_level`:

In [54]:
atemp_level.sample(5)          

8470     (0.25, 0.5]
7024     (0.25, 0.5]
2438     (0.25, 0.5]
15196    (0.25, 0.5]
1078     (0.5, 0.75]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [55]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

9845     cool
10111    mild
11675    warm
2684     warm
5898     warm
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [58]:
#ANSWER

bikes['atemp_level'] = atemp_level

bikes[bikes['season'] == 2]['atemp_level'].value_counts()

warm    2392
mild    1829
hot       98
cool      90
Name: atemp_level, dtype: int64

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

In [59]:
print(bikes['atemp_level'].dtype)

category


# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [60]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [62]:
for item in [a, b, c, d, e]:
    print(item.shape)
    print(item)
    print("\n")

(3,)
[0. 0. 0.]


(1, 3)
[[1. 1. 1.]]


(2, 3, 4)
[[[2 2 1 2]
  [3 7 5 6]
  [7 4 6 8]]

 [[4 3 4 9]
  [6 8 5 3]
  [5 3 5 2]]]


(4,)
[0 1 2 3]


(2, 4)
[[1 2 3 4]
 [5 6 7 8]]




# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [118]:
# Load rock dataset

rock = pd.read_csv("../../data/rock.csv")

rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [119]:
# Print column names

rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [120]:
# Clean columns

rock.columns = ['song_title', 'artist', 'release_year', 'song_artist_combined', 
                'first', 'year_available', 'play_count', 'play_count_if_year_found']

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [129]:
rock.isnull().sum()

song_title                    0
artist                        0
release_year                577
song_artist_combined          0
first                         0
year_available                0
play_count                    0
play_count_if_year_found      0
dtype: int64

In [70]:
# Check if release_year has null values 

rock['release_year'].isnull().sum()

577

In [72]:
# Fill release_year null values with 0

rock['release_year'] = rock['release_year'].fillna(0)

# Check that release_year has no null values

rock['release_year'].isnull().sum()

0

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [73]:
# Check datatypes

rock.dtypes

song_title                  object
artist                      object
release_year                object
song_artist_combined        object
first                        int64
year_available               int64
play_count                   int64
play_count_if_year_found     int64
dtype: object

In [74]:
# Change release_year into int 

rock['release_year'] = rock['release_year'].astype(int)

ValueError: invalid literal for int() with base 10: 'SONGFACTS.COM'

In [76]:
# Check release_year values

rock['release_year'].value_counts()

0                577
1973             104
1977              83
1975              83
1970              81
1971              75
1969              72
1980              70
1978              64
1979              63
1967              61
1981              61
1983              60
1976              56
1982              54
1984              51
1972              50
1974              48
1968              46
1985              39
1987              39
1986              37
1991              34
1989              32
1966              30
1988              29
1965              28
1994              25
1990              22
1993              19
1964              14
1992              14
1999              13
1995              10
1963               9
1996               9
1997               9
2002               6
1998               6
2012               5
2004               5
2005               5
2001               4
1962               3
2000               3
2003               3
2007               3
2008         

In [78]:
# apply function: if value is not int, change to 0

rock['release_year'] = rock['release_year'].apply(lambda x: 0 if str(x).isdigit() == False else x)

In [79]:
# Check release_year values, 0 should have 578 values now

rock['release_year'].value_counts()[:5]

0       578
1973    104
1977     83
1975     83
1970     81
Name: release_year, dtype: int64

In [82]:
# Convert release_year to int

rock['release_year'] = rock['release_year'].astype(int)

rock.dtypes

song_title                  object
artist                      object
release_year                 int64
song_artist_combined        object
first                        int64
year_available               int64
play_count                   int64
play_count_if_year_found     int64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [89]:
rock.describe(include='all')

song_title       artist  release_year  \
count                        2230         2230   2230.000000   
unique                       2158          475           NaN   
top     Knockin' On Heaven's Door  The Beatles           NaN   
freq                            3          100           NaN   
mean                          NaN          NaN   1465.331390   
std                           NaN          NaN    867.196161   
min                           NaN          NaN      0.000000   
25%                           NaN          NaN      0.000000   
50%                           NaN          NaN   1973.000000   
75%                           NaN          NaN   1981.000000   
max                           NaN          NaN   2014.000000   

                                song_artist_combined   first  year_available  \
count                                           2230  2230.0     2230.000000   
unique                                          2230     NaN             NaN   
top     Take The Highway by The Marshall Tucker Band     NaN             NaN   
freq                                               1     NaN             NaN   
mean                                             NaN     1.0        0.741256   
std                                              NaN     0.0        0.438043   
min                                              NaN     1.0        0.000000   
25%                                              NaN     1.0        0.000000   
50%                                              NaN     1.0        1.000000   
75%                                              NaN     1.0        1.000000   
max                                              NaN     1.0        1.000000   

         play_count  play_count_if_year_found  
count   2230.000000               2230.000000  
unique          NaN                       NaN  
top             NaN                       NaN  
freq            NaN                       NaN  
mean      16.872646                 15.048430  
std       25.302972                 25.288366  
min        0.000000                  0.000000  
25%        1.000000                  0.000000  
50%        4.000000                  3.000000  
75%       21.000000                 18.000000  
max      142.000000                142.000000

In [93]:
# Check that song titles are filled in

for i in rock['song_title'].tolist():
    if len(i) < 1:
        print(i)
        
# Check if song and artist title is filled in

for i in rock['song_artist_combined'].tolist():
    if len(i) < 1:
        print(i)

# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [84]:
def print_song_info(df_row):
    
    if df_row['release_year'] < 1970:
        print("{} released before 1970".format(df_row['song_artist_combined']))
    else:
        print("{} released in {}".format(df_row['song_artist_combined'], df_row['release_year']))

In [85]:
print_song_info(rock.iloc[0])

Caught Up in You by .38 Special released in 1982


## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [107]:
def convert_numeric_to_float(df):
    return df.astype('float', errors='coerce')

## Apply these functions to your dataset

In [109]:
for i in range(5):
    print_song_info(rock.iloc[i])

Caught Up in You by .38 Special released in 1982
Fantasy Girl by .38 Special released before 1970
Hold On Loosely by .38 Special released in 1981
Rockin' Into the Night by .38 Special released in 1980
Art For Arts Sake by 10cc released in 1975


In [108]:
convert_numeric_to_float(rock)

release_year  first  year_available  play_count  \
0           1982.0    1.0             1.0        82.0   
1              0.0    1.0             0.0         3.0   
2           1981.0    1.0             1.0        85.0   
3           1980.0    1.0             1.0        18.0   
4           1975.0    1.0             1.0         1.0   
5           2000.0    1.0             1.0        13.0   
6           2000.0    1.0             1.0         1.0   
7           2002.0    1.0             1.0         6.0   
8           1992.0    1.0             1.0         3.0   
9           1985.0    1.0             1.0         1.0   
10             0.0    1.0             0.0         1.0   
11          1980.0    1.0             1.0        97.0   
12          1993.0    1.0             1.0         6.0   
13             0.0    1.0             0.0         5.0   
14          1976.0    1.0             1.0        85.0   
15          1981.0    1.0             1.0        46.0   
16             0.0    1.0             0.0        24.0   
17          1995.0    1.0             1.0         1.0   
18          1980.0    1.0             1.0        39.0   
19          1980.0    1.0             1.0        74.0   
20          1979.0    1.0             1.0        92.0   
21          1975.0    1.0             1.0        39.0   
22          1984.0    1.0             1.0         1.0   
23          1977.0    1.0             1.0         3.0   
24             0.0    1.0             0.0         4.0   
25             0.0    1.0             0.0         2.0   
26             0.0    1.0             0.0        20.0   
27          1979.0    1.0             1.0         1.0   
28          1980.0    1.0             1.0        21.0   
29             0.0    1.0             0.0        45.0   
...            ...    ...             ...         ...   
2200        1983.0    1.0             1.0        81.0   
2201        1971.0    1.0             1.0        44.0   
2202        1971.0    1.0             1.0         1.0   
2203           0.0    1.0             0.0         5.0   
2204        1971.0    1.0             1.0         1.0   
2205           0.0    1.0             0.0         2.0   
2206           0.0    1.0             0.0         1.0   
2207        1968.0    1.0             1.0        14.0   
2208           0.0    1.0             0.0         1.0   
2209        1976.0    1.0             1.0         1.0   
2210        1973.0    1.0             1.0         8.0   
2211        1980.0    1.0             1.0        34.0   
2212        1983.0    1.0             1.0        86.0   
2213        1983.0    1.0             1.0        29.0   
2214        1975.0    1.0             1.0         2.0   
2215           0.0    1.0             0.0        16.0   
2216           0.0    1.0             0.0        10.0   
2217        1973.0    1.0             1.0         6.0   
2218           0.0    1.0             0.0         2.0   
2219        1973.0    1.0             1.0       111.0   
2220        1983.0    1.0             1.0       121.0   
2221           0.0    1.0             0.0         1.0   
2222           0.0    1.0             0.0        14.0   
2223        1981.0    1.0             1.0         5.0   
2224        1983.0    1.0             1.0       120.0   
2225           0.0    1.0             0.0         1.0   
2226        1981.0    1.0             1.0        32.0   
2227        1975.0    1.0             1.0       109.0   
2228        1983.0    1.0             1.0         1.0   
2229        1973.0    1.0             1.0         2.0   

      play_count_if_year_found  
0                         82.0  
1                          0.0  
2                         85.0  
3                         18.0  
4                          1.0  
5                         13.0  
6                          1.0  
7                          6.0  
8                          3.0  
9                          1.0  
10                         0.0  
11                        97.0  
12                         6.0  
13       

## Describe the new float-only DataFrame.

In [110]:
convert_numeric_to_float(rock).describe()

release_year   first  year_available   play_count  \
count   2230.000000  2230.0     2230.000000  2230.000000   
mean    1465.331390     1.0        0.741256    16.872646   
std      867.196161     0.0        0.438043    25.302972   
min        0.000000     1.0        0.000000     0.000000   
25%        0.000000     1.0        0.000000     1.000000   
50%     1973.000000     1.0        1.000000     4.000000   
75%     1981.000000     1.0        1.000000    21.000000   
max     2014.000000     1.0        1.000000   142.000000   

       play_count_if_year_found  
count               2230.000000  
mean                  15.048430  
std                   25.288366  
min                    0.000000  
25%                    0.000000  
50%                    3.000000  
75%                   18.000000  
max                  142.000000



> 
>
>




>


>


>




---



---

> > > > > > > >   © 2019 Data Science Institute of Australia


---



---

